name: Run RSS Main

on:
  schedule:
    - cron: '00 23 * * *'
    - cron: '24 01 * * *' 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      TO_ADDRESS: ${{ secrets.TO_ADDRESS }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
  
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
  
    - name: Run RSS main.py
      run: |
        python RSS/main.py
